name: "Tagging workflow"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v1"
      - name: "tag"
        uses: "./auto-increment-tag"
        with:
          git-token: ${{ secrets.GITHUB_TOKEN }}
      - name: "merge main back to dev"
        run: |
          git fetch
          git checkout develop
          git merge origin/main
          echo git push https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
          git push https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
