name: "Tagging workflow"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v1"
      - name: "tag"
        uses: "./auto-increment-tag"
        with:
          git-token: ${{ secrets.GITHUB_TOKEN }}
      - name: "merge main back to dev"
        run: |
          git fetch
          git checkout develop
          git merge origin/main
          git config --global user.name 'AlexanderCurtin'
          git config --global user.email 'AlexanderCurtin@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin develop
