name: "Tagging workflow"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v1"
      - name: "tag"
        uses: "./auto-increment-tag"
        inputs:
          github-token: ${{ secrets.GITHUB_TOKEN }}
