name: "Tagging workflow"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v1"
      - name: "tag"
        uses: "./auto-increment-tag"
        with:
          git-token: ${{ secrets.GITHUB_TOKEN }}
      - name: "merge main back to dev"
        run: |
          git fetch
          git checkout develop
          git merge origin/main
          export REPO_BASE=$(git remote -v | head -n 1 | awk '{print $2} | sed -E 's|^.*//||')
          echo git push https://$GITHUB_ACTOR:$GITHUB_TOKEN@$REPO_BASE
          git push https://$GITHUB_ACTOR:$GITHUB_TOKEN@$REPO_BASE
